In [ ]:
import numpy as np
import pandas as pd
import requests
import re

In [ ]:
url="https://d3c33hcgiwev3.cloudfront.net/_9b0d0ff87935997de01d221fd74bae90_categories.txt?Expires=1592265600&Signature=Qn9VLV24raH2cnYhMo907jwloeuWjz1RQnUI6KHUCIjkwTKxeTLaAqY7Vh1QnNyHLgNJJk8IrdTzax19phI7bCoWbIb5KLvS862E9Ler1qo262expFbmK6k~xTfe~zoF9c1LFnAjVbqTjphFBxbIq3-11t5EtfDm5n9Fob3Aptk_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A"
file=str(requests.get(url).content)
data=file.rsplit(";")
data=file.rsplit("\\n")

In [ ]:
del data[-1]

In [ ]:
list1=list()

In [ ]:
for i in range(77185):
  var=data[i]
  var=var.rsplit(";")
  list1.append(var)

In [ ]:
a=list1[0]
a[0]='Breakfast & Brunch'
list1[0]=a
list1[0]

['Breakfast & Brunch', 'American (Traditional)', 'Restaurants']

In [ ]:
#data=pd.DataFrame(list1)
#data.head()

In [ ]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.6/dist-packages (1.1.2)

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(list1).transform(list1)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [ ]:
df.head()

   ATV Rentals/Tours  Accessories  Accountants  ...  Yelp Events   Yoga   Zoos
0              False        False        False  ...        False  False  False
1              False        False        False  ...        False  False  False
2              False        False        False  ...        False  False  False
3              False        False        False  ...        False  False  False
4              False        False        False  ...        False  False  False

[5 rows x 892 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori
pattern = apriori(df,min_support = 0.01,use_colnames=True)
pattern['support']=(pattern['support']*77185)+1
pattern['support']=pattern['support'].astype(int)

In [ ]:
pattern.head(50)

    support                     itemsets
0      3104                (Active Life)
1      1594             (American (New))
2      2417     (American (Traditional))
3      2272       (Arts & Entertainment)
4      1717                (Auto Repair)
5      4209                 (Automotive)
6      1116                   (Bakeries)
7      4329                       (Bars)
8      6584              (Beauty & Spas)
9      1370         (Breakfast & Brunch)
10     1775                    (Burgers)
11     1003                      (Cafes)
12     1630                    (Chinese)
13     2200               (Coffee & Tea)
14     1196                   (Dentists)
15     1695                    (Doctors)
16     2976  (Event Planning & Services)
17     3079                    (Fashion)
18     2852                  (Fast Food)
19      876         (Financial Services)
20     1443      (Fitness & Instruction)
21     9251                       (Food)
22      824          (General Dentistry)
23     1425                    (Grocery)
24     2092                (Hair Salons)
25     5121           (Health & Medical)
26     1587              (Home & Garden)
27     4786              (Home Services)
28     1431                     (Hotels)
29     2496            (Hotels & Travel)
30     1019  (Ice Cream & Frozen Yogurt)
31     1849                    (Italian)
32      849                   (Japanese)
33     3469             (Local Services)
34     2516                    (Mexican)
35     1668                (Nail Salons)
36     5089                  (Nightlife)
37      871               (Pet Services)
38     1498                       (Pets)
39     2658                      (Pizza)
40     1026      (Professional Services)
41      875                       (Pubs)
42     1425                (Real Estate)
43    25072                (Restaurants)
44     2365                 (Sandwiches)
45    11234                   (Shopping)
46     1151             (Specialty Food)
47      819                (Sports Bars)
48      799                 (Sushi Bars)
49     1139           (Women's Clothing)

In [ ]:
#frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
##frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
#frequent_itemsets.head()

In [ ]:
length1=pattern.head(50)

In [ ]:
np.savetxt('length1.txt', length1.values, fmt='%s', delimiter=":", header="Support\t\tItemset") 
np.savetxt('patterns.txt', pattern.values, fmt='%s', delimiter=":", header="Support\t\tItemset")

In [ ]:
from google.colab import files
files.download("length1.txt")
files.download("patterns.txt")

In [ ]:

#association_results = list(Asso_rule)

In [ ]:
#association_results

[RelationRecord(items=frozenset({'Nightlife', 'Bars'}), support=0.05607379767827529, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bars'}), items_add=frozenset({'Nightlife'}), confidence=1.0, lift=15.169811320754716), OrderedStatistic(items_base=frozenset({'Nightlife'}), items_add=frozenset({'Bars'}), confidence=0.85062893081761, lift=15.169811320754716)])]